global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: tarpon
    scrape_interval: 5s
    static_configs:
      - targets:
          - tarpon:5000
